config/routes.rb
Rails.application.routes.draw do

  resources :homes

  resources :loans do
    collection do
      get :loan
    end
  end

  resources :sales

  resources :cars

  resources :staffs

  resources :customers

  root 'homes#index'

end

app/models/staff.rb
class Staff < ActiveRecord::Base
  has_many :sales
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form' %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
#encoding: UTF-8
<p id="notice"><%= notice %></p>

<header>
  <h1>Ogden Automotive</h1>
</header>

<nav>
<h1>Listing Staff</h1>
</nav>

<section>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.name %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</section>
<br>

<footer>
<%= link_to 'New Staff', new_staff_path %>
</footer>

app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form' %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>