config/routes.rb
Rails.application.routes.draw do

  resources :homes

  resources :loans do
    collection do
      get :loan
    end
  end

  resources :sales

  resources :cars

  resources :staffs

  resources :customers

  root 'homes#index'

end

app/models/loan.rb
class Loan < ActiveRecord::Base
  def self.payment
    @@payment
  end

  def self.amort_table(price = 0.00, interest_rate = 0.00, period = 0)
    Rails.logger.debug "Inputs: #{price} #{interest_rate} #{period}"
    loan = []
    fixed = price
    (1..period*12).each do |counter|
      period_rate = interest_rate/12
      @@payment = ((period_rate*fixed)/(1-(1+period_rate)**(-period*12)))
      loan << price - (@@payment - (price*interest_rate))

      last = price - (@@payment - (price*period_rate))

      price = last
    end
    return loan
  end

  def amort_table
    return self.class.amort_table(self.price, self.interest_rate, self.period)
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  def loan
    price =params[:price]
    interest_rate=params[:interest_rate]
    period=params[:period]
    @loan_array = Loan.amort_table(price.to_d, interest_rate.to_d, period.to_i)
  end

  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
    @loan_array = @loan.amort_table
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:price, :interest_rate, :period)
    end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<%= form_for(@loan) do |f| %>
  <% if @loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% @loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :interest_rate %><br>
    <%= f.text_field :interest_rate %>
  </div>
  <div class="field">
    <%= f.label :period %><br>
    <%= f.number_field :period %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<div id = "loan_table" class = "table-format"></div>

app/views/loans/_loan.erb
<table class="CSSTableGenerator" width="30%">
  <th>Price</th>
  <th>Price</th>
  <th>Interest Rate</th>
  <% @loan_array.each_with_index do |p,n|  %>
      <tr>
        <td><%= n %></td>
        <td><%= p.round(2) %></td>
        <td><%= Loan.payment.round(2) %></td>
      </tr>
  <% end %>

</table>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form' %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
#encoding: UTF-8
<p id="notice"><%= notice %></p>

<header>
  <h1>Ogden Automotive</h1>
</header>

<nav>
<h1>Listing Loans</h1>
</nav>

<section>
<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Interest Rate</th>
      <th>Period</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.price %></td>
        <td><%= number_with_precision(loan.interest_rate, precision: 2) %></td>
        <td><%= loan.period %></td>
        <td><%= link_to 'Show', loan %></td>
        <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
        <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</section>
<br>
<footer>
<%= link_to 'New Loan', new_loan_path %>
</footer>

app/views/loans/loan.js.erb
$('#loan_table').html("<%= j (render 'loan') %>")

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form' %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Price:</strong>
  <%= @loan.price %>
</p>

<p>
  <strong>Interest rate:</strong>
  <%= @loan.interest_rate %>
</p>

<p>
  <strong>Period:</strong>
  <%= @loan.period %>
</p>

<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', loans_path %>