config/routes.rb
Rails.application.routes.draw do

  resources :homes

  resources :loans do
    collection do
      get :loan
    end
  end

  resources :sales

  resources :cars

  resources :staffs

  resources :customers

  root 'homes#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :car
  belongs_to :customer
  belongs_to :staff

  @@markval=0.10
  @@tax=0.043

  def sold
    if self.status == false
      return "Not Sold"
    else
      return "Sold"
    end
  end

  def calc
    markups = (msrp + (msrp * @@markval))
    return markups
  end

  def taxx
    tax_total = (calc_total * @@tax)
    return tax_total
  end

  def marks
    mark = (msrp * 0.10)
    return mark
  end

  def calc_total
    final = ((calc + (calc * @@tax) + (calc * interest)) - principal)
    return final
  end

  def self.grevenue
    gross=0
    Sale.all.each do |counter|
      if counter.status == true
        gross += counter.calc_total
      end
    end
    return gross
  end

  def self.netprofit
    net=0
    Sale.all.each do |money|
      if money.status == true
        net += money.marks
      end
    end
    return net
  end

  def self.taxtotal
    tax=0
    Sale.all.each do |taxes|
      if taxes.status == true
        tax += taxes.taxx
      end
    end
    return tax
  end


end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:msrp, :markup, :interest, :principal, :total, :status, :customer_id, :staff_id, :car_id)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :msrp %><br>
    <%= f.text_field :msrp %>
  </div>
  <div class="field">
    <%= f.label :interest %><br>
    <%= f.text_field :interest %>
  </div>
  <div class="field">
    <%= f.label :principal %><br>
    <%= f.text_field :principal %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status%>
  </div>
  <div class="field">
    <%= f.label :Customer %><br>
    <%= f.collection_select :customer_id, Customer.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :Staff %><br>
    <%= f.collection_select :staff_id, Staff.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :VIN %><br>
    <%= f.collection_select :car_id, Car.all, :id, :model %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
#encoding: UTF-8
<p id="notice"><%= notice %></p>

<header>
  <h1>Ogden Automotive</h1>
</header>

<nav>
<h1>Listing Sales</h1>
</nav>

<section>
<table>
  <thead>
    <tr>
      <th>MSRP</th>
      <th>Markup</th>
      <th>Interest</th>
      <th>Principal</th>
      <th>Total</th>
      <th>Status</th>
      <th>Customer</th>
      <th>Assigned Sales Staff</th>
      <th>Car</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= number_to_currency(sale.msrp, :unit => "$", :delimeter => ".") %></td>
        <td><%= number_to_currency(sale.calc, :unit => "$", :delimeter => ".") %></td>
        <td><%= number_with_precision(sale.interest, precision: 2) %></td>
        <td><%= number_to_currency(sale.principal, :unit => "$", :delimeter => ".") %></td>
        <td><%= number_to_currency(sale.calc_total, :unit => "$", :delimeter => ".") %></td>
        <td><%= sale.sold %></td>
        <td><%= sale.customer.name %></td>
        <td><%= sale.staff.name %></td>
        <td><%= sale.car.model %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table><br/><br/>

  <h1>Dealership Owner Information</h1>
  <th>
Total Gross Revenue= </th><td> <%= number_to_currency(Sale.grevenue, :unit => "$", :delimeter => ".") %></td>
<br>
Net Profit= </th><td> <%= number_to_currency(Sale.netprofit, :unit => "$", :delimeter => ".") %></td>
<br>
Sales Tax Total = </th><td> <%= number_to_currency(Sale.taxtotal, :unit => "$", :delimeter => ".") %></td>
<br>
</section>
<footer>
<%= link_to 'New Sale', new_sale_path %>
</footer>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Msrp:</strong>
  <%= @sale.msrp %>
</p>

<p>
  <strong>Markup:</strong>
  <%= @sale.markup %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @sale.interest %>
</p>

<p>
  <strong>Principal:</strong>
  <%= @sale.principal %>
</p>

<p>
  <strong>Total:</strong>
  <%= @sale.total %>
</p>

<p>
  <strong>Sold?</strong>
  <%= @sale.status %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @sale.customer_id %>
</p>

<p>
  <strong>Staff:</strong>
  <%= @sale.staff_id %>
</p>

<p>
  <strong>Car:</strong>
  <%= @sale.car_id %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>